language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.9.7
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.10a1
# command to install dependencies
install:
  - pip install Django~=$DJANGO_VERSION
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: "./run_tests.sh"
